### ISSUE TITLE
Things to work on at the QPL2023 hackathon

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#47]
Small things:

- [x] Change colours for selection?
- [x] Support panning (this is actually easier than you think). [Agustín]
- [x] Magic wand UI improvements (#40). [Tuomas]
- [x] More and sexier animations (see also #46).
- [x] Make positioning of spiders after drag bialgebra action better (see #41).
- [x] When in selection mode, let shift-clicking add things to selection (see #23). [Tiffany]
- [x] In Proof mode, do colour change by double clicking? [Julien]
- [x] Better phase inputs when double-clicking in edit mode (support expressions like 'pi/2' or even 'alpha'). [Razin]
- [x] Make ZXLive more mypy compliant. [Boldi]
- [x] When new vertices are added by a rewrite, make sure these vertices are selected. [Agustín]

Medium things:
- [x] Make magic wand smarter by detecting which edges exactly you want to unfuse. [Tuomas]
- [x] Magic wand: drag across edge to add identity.
- [x] #50
- [x] Allow printing of matrix representing the diagram and checking changes. [Richie]
- [x] Add toolbar in Proof mode for bringing to several normal forms.
- [ ] Sound effects?
- [x] Implement H-boxes (easier than you think, just use PyZX things).
- [x] #135
- [x] Make ZXLive Python 3.9 compatible. [Richie]

Big things:
- [x] Start derivation panel tracking all your proof steps. [Aleks/Mark]
- [x] #63
- [ ] #101

**Comment by jvdwetering** [comment]
Closing this as it is mostly implemented and has served its purpose.
